name: Deploy Angular App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        working-directory: ./my-angular-app
        run: npm install

      - name: Build Angular application
        working-directory: ./my-angular-app
        run: ng build --configuration=production

      - name: Archive build files
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          ZIP_NAME="my-angular-app-$TIMESTAMP.zip"
          cd ./my-angular-app/dist/my-angular-app
          zip -r $ZIP_NAME .
          mv $ZIP_NAME ../../..
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./my-angular-app/dist/my-angular-app/$ZIP_NAME

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          aws s3 cp ./my-angular-app/$ZIP_NAME s3://my-angular-app-bucket/$ZIP_NAME
          aws elasticbeanstalk create-application-version --application-name my-angular-app --version-label ${{ github.sha }} --source-bundle S3Bucket=my-angular-app-bucket,S3Key=$ZIP_NAME
          aws elasticbeanstalk update-environment --environment-name my-angular-app-env --version-label ${{ github.sha }}
